ALTER TABLE `foodie_vlog`.`post` 
CHANGE COLUMN `services` `services` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `cleanliness` `cleanliness` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `taste` `taste` DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN `price` `price` DOUBLE NULL DEFAULT NULL ;